### ISSUE TITLE
依赖管理

### ISSUE THREAD

**Issue by fzdwx** [Chanyon/Xjournal#1]
这个 zig 依赖管理这么难受吗，还有你其他依赖都传了，`zig-toml` 这个咋没传

**Comment by Chanyon** [comment]
> 这个 zig 依赖管理这么难受吗，还有你其他依赖都传了，`zig-toml` 这个咋没传

zig包管理器要0.11发布后才可用，现在只能自己手动下载。`zig-toml`上传的时候没处理，0.11之后也会删除dep文件夹。
